from PyQt5 import QtCore, QtGui, QtWidgets
import numpy as np
import pickle

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(743, 415)
        self.instructions_lbl = QtWidgets.QLabel(Dialog)
        self.instructions_lbl.setGeometry(QtCore.QRect(20, 20, 321, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.instructions_lbl.setFont(font)
        self.instructions_lbl.setObjectName("instructions_lbl")
        self.check_button = QtWidgets.QPushButton(Dialog)
        self.check_button.setGeometry(QtCore.QRect(330, 280, 91, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.check_button.setFont(font)
        self.check_button.setObjectName("check_button")
        self.v1_lbl = QtWidgets.QLabel(Dialog)
        self.v1_lbl.setGeometry(QtCore.QRect(20, 80, 31, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.v1_lbl.setFont(font)
        self.v1_lbl.setObjectName("v1_lbl")
        self.v2_lbl = QtWidgets.QLabel(Dialog)
        self.v2_lbl.setGeometry(QtCore.QRect(200, 80, 31, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.v2_lbl.setFont(font)
        self.v2_lbl.setObjectName("v2_lbl")
        self.v3_lbl = QtWidgets.QLabel(Dialog)
        self.v3_lbl.setGeometry(QtCore.QRect(380, 80, 31, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.v3_lbl.setFont(font)
        self.v3_lbl.setObjectName("v3_lbl")
        self.v4_lbl = QtWidgets.QLabel(Dialog)
        self.v4_lbl.setGeometry(QtCore.QRect(560, 80, 31, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.v4_lbl.setFont(font)
        self.v4_lbl.setObjectName("v4_lbl")
        self.v9_lbl = QtWidgets.QLabel(Dialog)
        self.v9_lbl.setGeometry(QtCore.QRect(20, 130, 31, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.v9_lbl.setFont(font)
        self.v9_lbl.setObjectName("v9_lbl")
        self.v11_lbl = QtWidgets.QLabel(Dialog)
        self.v11_lbl.setGeometry(QtCore.QRect(380, 130, 41, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.v11_lbl.setFont(font)
        self.v11_lbl.setObjectName("v11_lbl")
        self.v10_lbl = QtWidgets.QLabel(Dialog)
        self.v10_lbl.setGeometry(QtCore.QRect(200, 130, 41, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.v10_lbl.setFont(font)
        self.v10_lbl.setObjectName("v10_lbl")
        self.v12_lbl = QtWidgets.QLabel(Dialog)
        self.v12_lbl.setGeometry(QtCore.QRect(560, 130, 41, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.v12_lbl.setFont(font)
        self.v12_lbl.setObjectName("v12_lbl")
        self.v14_lbl = QtWidgets.QLabel(Dialog)
        self.v14_lbl.setGeometry(QtCore.QRect(100, 180, 41, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.v14_lbl.setFont(font)
        self.v14_lbl.setObjectName("v14_lbl")
        self.v18_lbl = QtWidgets.QLabel(Dialog)
        self.v18_lbl.setGeometry(QtCore.QRect(270, 180, 41, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.v18_lbl.setFont(font)
        self.v18_lbl.setObjectName("v18_lbl")
        self.S_Amount_lbl = QtWidgets.QLabel(Dialog)
        self.S_Amount_lbl.setGeometry(QtCore.QRect(230, 230, 91, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.S_Amount_lbl.setFont(font)
        self.S_Amount_lbl.setObjectName("S_Amount_lbl")
        self.v19_lbl = QtWidgets.QLabel(Dialog)
        self.v19_lbl.setGeometry(QtCore.QRect(460, 180, 41, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.v19_lbl.setFont(font)
        self.v19_lbl.setObjectName("v19_lbl")
        self.result_lbl = QtWidgets.QLabel(Dialog)
        self.result_lbl.setGeometry(QtCore.QRect(130, 330, 481, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.result_lbl.setFont(font)
        self.result_lbl.setText("")
        self.result_lbl.setObjectName("result_lbl")
        self.v1_input = QtWidgets.QLineEdit(Dialog)
        self.v1_input.setGeometry(QtCore.QRect(60, 90, 113, 22))
        self.v1_input.setObjectName("v1_input")
        self.v19_input = QtWidgets.QLineEdit(Dialog)
        self.v19_input.setGeometry(QtCore.QRect(500, 190, 113, 22))
        self.v19_input.setObjectName("v19_input")
        self.v11_input = QtWidgets.QLineEdit(Dialog)
        self.v11_input.setGeometry(QtCore.QRect(420, 140, 113, 22))
        self.v11_input.setObjectName("v11_input")
        self.v18_input = QtWidgets.QLineEdit(Dialog)
        self.v18_input.setGeometry(QtCore.QRect(320, 190, 113, 22))
        self.v18_input.setObjectName("v18_input")
        self.v9_input = QtWidgets.QLineEdit(Dialog)
        self.v9_input.setGeometry(QtCore.QRect(60, 140, 113, 22))
        self.v9_input.setObjectName("v9_input")
        self.v2_input = QtWidgets.QLineEdit(Dialog)
        self.v2_input.setGeometry(QtCore.QRect(240, 90, 113, 22))
        self.v2_input.setObjectName("v2_input")
        self.v10_input = QtWidgets.QLineEdit(Dialog)
        self.v10_input.setGeometry(QtCore.QRect(240, 140, 113, 22))
        self.v10_input.setObjectName("v10_input")
        self.v14_input = QtWidgets.QLineEdit(Dialog)
        self.v14_input.setGeometry(QtCore.QRect(140, 190, 113, 22))
        self.v14_input.setObjectName("v14_input")
        self.v3_input = QtWidgets.QLineEdit(Dialog)
        self.v3_input.setGeometry(QtCore.QRect(420, 90, 113, 22))
        self.v3_input.setObjectName("v3_input")
        self.S_Amount_input = QtWidgets.QLineEdit(Dialog)
        self.S_Amount_input.setGeometry(QtCore.QRect(320, 240, 113, 22))
        self.S_Amount_input.setObjectName("S_Amount_input")
        self.v12_input = QtWidgets.QLineEdit(Dialog)
        self.v12_input.setGeometry(QtCore.QRect(600, 140, 113, 22))
        self.v12_input.setObjectName("v12_input")
        self.v4_input = QtWidgets.QLineEdit(Dialog)
        self.v4_input.setGeometry(QtCore.QRect(600, 90, 113, 22))
        self.v4_input.setObjectName("v4_input")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.check_button.clicked.connect(self.detect_fraud)

    def detect_fraud(self):
        v1 = float(self.v1_input.text())
        v2 = float(self.v2_input.text())
        v3 = float(self.v3_input.text())
        v4 = float(self.v4_input.text())
        v9 = float(self.v9_input.text())
        v11 = float(self.v11_input.text())
        v10 = float(self.v10_input.text())
        v12 = float(self.v12_input.text())
        v14 = float(self.v14_input.text())
        v18 = float(self.v18_input.text())
        S_Amount = float(self.S_Amount_input.text())
        v19 = float(self.v19_input.text())
        data = [v1, v2, v3, v4, v9, v10, v11, v12, v14, v18, v19, S_Amount]
        array_data = np.asarray(data).reshape(1, -1)
        print(array_data)
        import pickle
        filename = 'Finalized_model_Poly_12F'
        with open(filename, 'rb') as file:
            Pickled_LR_Model = pickle.load(file)
            y_pred = Pickled_LR_Model.predict(array_data)
        print(y_pred)
        if y_pred == 1:
            self.result_lbl.setText("Fraud")
        else:
            self.result_lbl.setText("Not Fraud")

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Credit Card Fraud Detector"))
        self.instructions_lbl.setText(_translate("Dialog", "Please enter values for the features below:"))
        self.check_button.setText(_translate("Dialog", "Check"))
        self.v1_lbl.setText(_translate("Dialog", "V1:"))
        self.v2_lbl.setText(_translate("Dialog", "V2:"))
        self.v3_lbl.setText(_translate("Dialog", "V3:"))
        self.v4_lbl.setText(_translate("Dialog", "V4:"))
        self.v9_lbl.setText(_translate("Dialog", "V9:"))
        self.v11_lbl.setText(_translate("Dialog", "V11:"))
        self.v10_lbl.setText(_translate("Dialog", "V10:"))
        self.v12_lbl.setText(_translate("Dialog", "V12:"))
        self.v14_lbl.setText(_translate("Dialog", "V14:"))
        self.v18_lbl.setText(_translate("Dialog", "V18:"))
        self.S_Amount_lbl.setText(_translate("Dialog", "S_Amount:"))
        self.v19_lbl.setText(_translate("Dialog", "V19:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
